build: ch10.ml ch10_sub.ml ch10_bridge.ml ch10_typechecking.ml ch10_base.ml
	-mkdir _build
	cp ch10_sub.ml ch10_base.ml ch10_bridge.ml ch10_typechecking.ml ch10.ml _build
	cd _build && ocamlc  ch10_sub.ml ch10_base.ml ch10_bridge.ml ch10_typechecking.ml ch10.ml -o ch10
